New dashboard page
P3-Hype/SRAMS-frontend pull request #111
Opened 2023-11-14 15:04 UTC by alexrefshauge

### Additions
- Simple room status cards
- List suggested rooms sorted by air quality
- Small gauge for air quality (color is interpolated)

### Preview
![image](https://github.com/P3-Hype/SRAMS-frontend/assets/44145107/e8aaea2d-0d45-4ae7-96f3-f84b670b93ac)

### Notes
Maybe the gauge should show percentage instead?

2023-11-14 15:11 UTC, alexrefshauge commented
@MathiasFM 😖😭 
![image](https://github.com/P3-Hype/SRAMS-frontend/assets/44145107/2ad0fed2-5c6b-481d-97b9-8ae38d3142ea)

2023-11-15 08:16 UTC, TobiasABay commented
> ### Additions
> * Simple room status cards
> * List suggested rooms sorted by air quality
> * Small gauge for air quality (color is interpolated)
> 
> ### Preview
> ![image](https://user-images.githubusercontent.com/44145107/282821099-e8aaea2d-0d45-4ae7-96f3-f84b670b93ac.png)
> 
> ### Notes
> Maybe the gauge should show percentage instead?

Its hard to see what the number means. Maybe a label with the specific metric could be an idea :)

2023-11-15 09:49 UTC, TobiasABay requested changes
Gør som jeg sagde i min kommentar samt ændre den til procent måske

2023-11-15 10:17 UTC, TobiasABay approved these changes

2023-11-15 10:17 UTC, merged