Added Header
P3-Hype/SRAMS-frontend pull request #15
Opened 2023-10-10 15:04 UTC by TobiasABay

2023-10-10 15:13 UTC, alexrefshauge requested changes

2023-10-10 15:13 UTC, alexrefshauge commented on src/components/Header/Header.tsx
> +            color: "white",
Brug MUI farver

2023-10-10 15:13 UTC, alexrefshauge commented on src/components/Header/Header.tsx
> +                    alignItems: "center",
Hvorfor? Burde ikke være nødvendigt

2023-10-10 15:13 UTC, alexrefshauge commented on src/components/Header/Header.tsx
> +function Header(){
Evt skriv props, hvori vi kan tilgå onClick events på knapperne

2023-10-12 08:10 UTC, MathiasFM commented
☠

2023-10-12 10:53 UTC, alexrefshauge approved these changes

2023-10-12 10:54 UTC, merged