Added a simple toggle, to display either as grid view or map view
P3-Hype/SRAMS-frontend pull request #18
Opened 2023-10-12 11:59 UTC by MathiasFM

This is purely cosmetic, and has no functionality yet.

Icons can be changed later.

![image](https://github.com/P3-Hype/SRAMS-frontend/assets/96435651/8a89e62a-2729-4e72-b970-6f26274e3581)

2023-10-12 12:17 UTC, TobiasABay requested changes
Havde forventet denne toggle:
https://mui.com/material-ui/react-switch/

2023-10-12 12:22 UTC, TobiasABay requested changes
Denne her fungere meget bedre end den jeg linkede til: https://mui.com/material-ui/react-switch/#customization

2023-10-12 12:31 UTC, alexrefshauge requested changes

2023-10-12 12:31 UTC, alexrefshauge commented on src/components/ToggleView/ToggleView.tsx
> +      aria-label="text alignment"
Tror du har glemt at ændre denne til noget relavant, måske "view mode" eller noget lignende

2023-10-12 12:31 UTC, alexrefshauge commented on src/components/ToggleView/ToggleView.tsx
> +      <ToggleButton value="left" aria-label="left aligned">
Samme her med aria-label

2023-10-12 12:31 UTC, alexrefshauge commented on src/components/ToggleView/ToggleView.tsx
> +      <ToggleButton value="right" aria-label="right aligned">
Samme her med aria-label

2023-10-12 12:31 UTC, alexrefshauge commented on src/components/Header/Header.tsx
> +                    <ToggleView></ToggleView>
Behøves ikke en ny Box, du kan bare ligge den ind i stacken nedenunder, så får spacing attributten også den ønskede effekt

2023-10-12 12:40 UTC, TobiasABay commented
> > Denne her fungere meget bedre end den jeg linkede til: https://mui.com/material-ui/react-switch/#customization
> 
> Noget i den her stil? ![image](https://user-images.githubusercontent.com/96435651/274598977-68ec417a-d174-40db-9c12-eab427f364ef.png) Ser bare lidt mærkeligt ud i forhold til UI.



> > Denne her fungere meget bedre end den jeg linkede til: https://mui.com/material-ui/react-switch/#customization
> 
> Noget i den her stil? ![image](https://user-images.githubusercontent.com/96435651/274598977-68ec417a-d174-40db-9c12-eab427f364ef.png) Ser bare lidt mærkeligt ud i forhold til UI.

Ja det fint

2023-10-12 13:31 UTC, alexrefshauge requested changes

2023-10-12 13:31 UTC, alexrefshauge commented on src/components/ToggleView/ToggleView.tsx
> +      <ToggleButton value="right" aria-label="right aligned">
Måske skal value også være noget mere relavant, såsom: "map" og "grid"

2023-10-12 17:40 UTC, MathiasFM commented
> > Noget i den her stil? ![image](https://user-images.githubusercontent.com/96435651/274598977-68ec417a-d174-40db-9c12-eab427f364ef.png) Ser bare lidt mærkeligt ud i forhold til UI.
> 
> Ja det fint

![image](https://github.com/P3-Hype/SRAMS-frontend/assets/96435651/429e93ca-7587-46e7-9670-e5eaf1b2ae77)
Case closed.

https://uxmovement.com/mobile/stop-misusing-toggle-switches/

2023-10-13 09:01 UTC, TobiasABay approved these changes

2023-10-13 09:09 UTC, alexrefshauge approved these changes

2023-10-13 09:10 UTC, merged