SUper nice og meget brugbare home page med navbuts
P3-Hype/SRAMS-frontend pull request #32
Opened 2023-10-16 12:04 UTC by LeUnioo

please <3

2023-10-16 12:10 UTC, alexrefshauge requested changes

2023-10-16 12:10 UTC, alexrefshauge commented on src/components/HomePage/NavButtons.tsx
> +            style={ButStyle}
Brug venligst sx attributten, da den kommer fra mui og er "fast as fuck"
https://mui.com/material-ui/react-box/#the-sx-prop

2023-10-18 08:29 UTC, LeUnioo reviewed
button fixed

2023-10-18 08:45 UTC, alexrefshauge approved these changes

2023-10-18 08:45 UTC, alexrefshauge commented
@LeUnioo Du kører den bare ind i main 😊

2023-10-18 11:32 UTC, merged