Added timeline
P3-Hype/SRAMS-frontend pull request #46
Opened 2023-10-23 16:17 UTC by TobiasABay

#SovseKode

2023-10-23 17:43 UTC, alexrefshauge requested changes

2023-10-23 17:43 UTC, alexrefshauge commented on src/pages/RoomOverviewPage.tsx
> +        </Container>
Kan bare være Box
```suggestion
        <Box>
          <Timeline rooms={rooms} />
        </Box>
```

2023-10-23 17:43 UTC, alexrefshauge commented on src/components/TimeClock/Timeline.tsx
> +            </div>
Vi har MUI - div og inline styles er langsomt 😁🦧
```suggestion
            <Box
              sx={{
                position: "relative",
                height: "20px",
                backgroundColor: "white",
                marginLeft: "16px",
              }}
            >
              {position !== null && (
                <Box
                  sx={{
                    position: "absolute",
                    left: `${position}%`,
                    top: 0,
                    bottom: 0,
                    width: "2px",
                    backgroundColor: "red",
                  }}
                />
              )}
            </Box>
```

2023-10-23 17:43 UTC, alexrefshauge commented on src/components/TimeClock/Timeline.tsx
> +  for (let i = 8; i <= 21; i++) {
Kan vi få variabler til 8 og 21 her?

2023-10-23 17:44 UTC, alexrefshauge commented
@TobiasABay 
Ser godt ud, lige et par små ændringer ellers er det en skide god start 🙌

2023-10-24 08:36 UTC, TobiasABay commented on src/components/TimeClock/Timeline.tsx
> +  for (let i = 8; i <= 21; i++) {
Jeg er lidt usikker på hvordan det skal gøres

2023-10-24 12:19 UTC, alexrefshauge commented on src/components/TimeClock/Timeline.tsx
> +  for (let i = 8; i <= 21; i++) {
Noget a la:
```js
const startTime = 8;
const endTime = 21;

const generateTimelineLabel = () => {
  const labels = [];
  for (let i = startTime; i <= endTime; i++) {
```

Men de skal vel ikke bare være konstanter?

2023-10-25 07:28 UTC, alexrefshauge approved these changes

2023-10-25 07:28 UTC, merged